/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux Zicolas-Laptop 5.0.0-32-generic x86_64"
#define LGL_COMPILED "Δευ 28 Οκτ 2019 02:01:17 μμ EET"
#define LGL_RELEASED "Fri Feb  7 22:21:52 CET 2014"
#define LGL_VERSION "ats1"
#define LGL_ID "ce8c04fc97ef07cf279c0c5dcbbc7c5d9904230a"
